language: php

php:
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0

before_script:
  - script/bootstrap
  - script/setup

script: script/cibuild

sudo: false
